# -*- coding: utf-8 -*-
"""TTS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jP9mRdF0Gq6ZGWd7ugbpn1pyfcUoVtUI
"""

!pip install requests

import xml.etree.ElementTree as ET 
speak = ET.Element("speak") 
voice1 = ET.Element("voice", name="WOMAN_READ_CALM") 
voice1.text = input()
speak.append(voice1) 
voice2 = ET.Element("voice", name="WOMAN_READ_CALM") 
voice2.text = "만나서 반가워요" 
speak.append(voice2) 
def indent(elem, level=0): 
    i = "\n" + level*" " 
    if len(elem): 
        if not elem.text or not elem.text.strip(): 
            elem.text = i + " " 
        if not elem.tail or not elem.tail.strip(): 
            elem.tail = i 
        for elem in elem: 
            indent(elem, level+1) 
        if not elem.tail or not elem.tail.strip(): 
            elem.tail = i 
    else: 
        if level and (not elem.tail or not elem.tail.strip()): 
            elem.tail = i 
indent(speak) 
ET.dump(speak)

ET.ElementTree(speak).write("data.xml", encoding="utf-8", xml_declaration=True)

import requests

kakao_tts_url = "https://kakaoi-newtone-openapi.kakao.com/v1/synthesize"
rest_api_key = "0238684eeaa7b043ef3d0e011ad3caab"

headers = {
    "Content-Type": "application/xml",
    "Authorization": "KakaoAK " + rest_api_key,
}
with open('data.xml', 'rb') as fp:
    data = fp.read()
res = requests.post(kakao_tts_url, headers=headers, data = data)
rescode = int(res.status_code)
if(rescode==200):
    print("TTS mp3 저장")
    response_body = res.content
    with open('1111.mp3', 'wb') as f:
        f.write(response_body)
else:
    print(rescode)